[2024-04-17 18:43:40,117] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:01,388] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:01] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:01,416] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:01] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:01,513] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:01] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:01,519] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:01] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:01,525] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:01] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,076] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,096] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,110] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,151] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,231] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:44:04,280] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:44:04] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 18:45:29,466] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 18:45:29] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:02,913] INFO _log() L224  [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.113:5000 - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:02,914] INFO _log() L224  [33mPress CTRL+C to quit[0m - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:05,112] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:05] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:05,121] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:05] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:05,204] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:05] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:05,204] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:05] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:05,204] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:05] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:06,297] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:06] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:06,314] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:06] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:06,318] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:06] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:06,370] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:06] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:25:06,452] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:25:06] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:26:04,200] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:26:04] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:26:49,479] WARNING add_cliente() L54   Erro ao adicionar cliente 'Simone Marta', Cliente de mesmo nome já salvo na base :/ - call_trace=C:\Users\renat\OneDrive\Desktop\MVP_cadastro de clientes\cadastro_cliente_api\app.py L54  
[2024-04-17 23:26:49,480] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:26:49] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:28:10,859] INFO _log() L224  127.0.0.1 - - [17/Apr/2024 23:28:10] "[31m[1mPUT /cliente HTTP/1.1[0m" 422 - - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-04-17 23:30:16,678] WARNING update_cliente() L103  Erro ao adicionar cliente 'Renato Lisboa', 'NoneType' object has no attribute 'nome' - call_trace=C:\Users\renat\OneDrive\Desktop\MVP_cadastro de clientes\cadastro_cliente_api\app.py L103 
[2024-04-17 23:30:16,679] ERROR log_exception() L1449 Exception on /cliente [PUT] - call_trace=C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1714, in make_response
    rv = jsonify(rv)
         ^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\json\__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\json\__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\json\__init__.py", line 51, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\renat\AppData\Local\Programs\Python\Python312\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
